[2025-04-27 17:15:55,623: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-27 17:15:55,624: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-27 17:15:55,626: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-27 17:15:55,626: INFO: common: created directory at: artifacts]
[2025-04-27 17:15:55,626: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-27 17:15:55,626: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-27 17:16:59,534: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-27 17:16:59,861: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-27 17:16:59,861: INFO: main: *******************]
[2025-04-27 17:16:59,861: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-27 17:16:59,862: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-27 17:16:59,863: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-27 17:16:59,863: INFO: common: created directory at: artifacts]
[2025-04-27 17:16:59,863: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-27 17:18:03,738: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-27 17:18:03,870: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-27 17:18:03,870: INFO: main: *******************]
[2025-04-27 17:18:03,871: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-27 17:18:03,872: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-27 17:18:03,873: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-27 17:18:03,873: INFO: common: created directory at: artifacts]
[2025-04-27 17:18:03,873: INFO: common: created directory at: artifacts/training]
[2025-04-27 17:18:04,136: ERROR: main: Could not import PIL.Image. The use of `load_img` requires PIL.]
Traceback (most recent call last):
  File "/home/louay/PycharmProjects/KidneyDisease/main.py", line 42, in <module>
    model_trainer.main()
  File "/home/louay/PycharmProjects/KidneyDisease/cnnClassifier/pipeline/stage_03_model_training.py", line 21, in main
    training.train()
  File "/home/louay/PycharmProjects/KidneyDisease/cnnClassifier/components/model_training.py", line 76, in train
    self.model.fit(
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/keras/utils/image_utils.py", line 414, in load_img
    raise ImportError(
ImportError: Could not import PIL.Image. The use of `load_img` requires PIL.
[2025-04-27 17:21:23,964: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-27 17:21:23,965: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-27 17:21:23,966: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-27 17:21:23,966: INFO: common: created directory at: artifacts]
[2025-04-27 17:21:23,966: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-27 17:21:23,966: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-27 17:22:31,903: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-27 17:22:32,301: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-27 17:22:32,301: INFO: main: *******************]
[2025-04-27 17:22:32,301: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-27 17:22:32,302: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-27 17:22:32,303: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-27 17:22:32,304: INFO: common: created directory at: artifacts]
[2025-04-27 17:22:32,304: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-27 17:22:34,269: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-27 17:22:34,477: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-27 17:22:34,477: INFO: main: *******************]
[2025-04-27 17:22:34,477: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-27 17:22:34,479: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-27 17:22:34,480: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-27 17:22:34,480: INFO: common: created directory at: artifacts]
[2025-04-27 17:22:34,480: INFO: common: created directory at: artifacts/training]
[2025-04-27 17:23:27,754: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-27 17:23:27,754: INFO: main: *******************]
[2025-04-27 17:23:27,754: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-04-27 17:23:27,756: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-27 17:23:27,757: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-27 17:23:27,757: INFO: common: created directory at: artifacts]
[2025-04-27 17:23:42,761: INFO: common: json file saved at: scores.json]
[2025-04-27 17:23:42,761: INFO: common: json file saved at: scores.json]
[2025-04-27 17:23:42,761: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-04-27 18:31:51,685: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8089
 * Running on http://192.168.1.15:8089]
[2025-04-27 18:31:51,685: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-04-27 18:31:57,046: INFO: _internal: 127.0.0.1 - - [27/Apr/2025 18:31:57] "GET / HTTP/1.1" 200 -]
[2025-04-27 18:31:57,414: INFO: _internal: 127.0.0.1 - - [27/Apr/2025 18:31:57] "[33mGET /Roboto-Regular.ttf HTTP/1.1[0m" 404 -]
[2025-04-27 18:32:13,351: INFO: _internal: 127.0.0.1 - - [27/Apr/2025 18:32:13] "POST /predict HTTP/1.1" 200 -]
[2025-04-27 18:33:44,793: INFO: _internal: 127.0.0.1 - - [27/Apr/2025 18:33:44] "POST /predict HTTP/1.1" 200 -]
[2025-04-27 22:12:08,801: INFO: _internal: 127.0.0.1 - - [27/Apr/2025 22:12:08] "POST /predict HTTP/1.1" 200 -]
[2025-04-27 22:12:30,348: INFO: _internal: 127.0.0.1 - - [27/Apr/2025 22:12:30] "POST /predict HTTP/1.1" 200 -]
[2025-04-27 22:13:46,486: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/flask_cors/decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/louay/PycharmProjects/KidneyDisease/app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "/home/louay/PycharmProjects/KidneyDisease/cnnClassifier/pipeline/prediction.py", line 19, in predict
    test_image = image.load_img(imagename, target_size = (224,224))
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/keras/utils/image_utils.py", line 423, in load_img
    img = pil_image.open(io.BytesIO(f.read()))
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/PIL/Image.py", line 3572, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x723100160c70>
[2025-04-27 22:13:46,488: INFO: _internal: 127.0.0.1 - - [27/Apr/2025 22:13:46] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-04-27 22:15:17,569: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/flask_cors/decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/louay/PycharmProjects/KidneyDisease/app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "/home/louay/PycharmProjects/KidneyDisease/cnnClassifier/pipeline/prediction.py", line 19, in predict
    test_image = image.load_img(imagename, target_size = (224,224))
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/keras/utils/image_utils.py", line 423, in load_img
    img = pil_image.open(io.BytesIO(f.read()))
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/PIL/Image.py", line 3572, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x723100228400>
[2025-04-27 22:15:17,570: INFO: _internal: 127.0.0.1 - - [27/Apr/2025 22:15:17] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-04-27 22:15:28,265: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/flask_cors/decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/louay/PycharmProjects/KidneyDisease/app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "/home/louay/PycharmProjects/KidneyDisease/cnnClassifier/pipeline/prediction.py", line 19, in predict
    test_image = image.load_img(imagename, target_size = (224,224))
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/keras/utils/image_utils.py", line 423, in load_img
    img = pil_image.open(io.BytesIO(f.read()))
  File "/home/louay/PycharmProjects/KidneyDisease/.venv3.10/lib/python3.10/site-packages/PIL/Image.py", line 3572, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7230effd3380>
[2025-04-27 22:15:28,265: INFO: _internal: 127.0.0.1 - - [27/Apr/2025 22:15:28] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-04-27 22:20:06,488: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7230eff4c8b0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-04-27 22:20:06,490: INFO: _internal: 127.0.0.1 - - [27/Apr/2025 22:20:06] "POST /predict HTTP/1.1" 200 -]
[2025-04-27 22:20:24,225: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7230eff4c9d0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-04-27 22:20:24,227: INFO: _internal: 127.0.0.1 - - [27/Apr/2025 22:20:24] "POST /predict HTTP/1.1" 200 -]
[2025-04-27 23:00:51,673: INFO: _internal: 127.0.0.1 - - [27/Apr/2025 23:00:51] "POST /predict HTTP/1.1" 200 -]
[2025-04-27 23:02:14,933: INFO: _internal: 127.0.0.1 - - [27/Apr/2025 23:02:14] "POST /predict HTTP/1.1" 200 -]
[2025-04-27 23:18:52,815: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-27 23:18:52,822: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-27 23:18:52,823: INFO: common: created directory at: artifacts]
[2025-04-27 23:18:52,824: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-27 23:18:52,825: INFO: 1554040998: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-27 23:19:46,375: INFO: 1554040998: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-27 23:21:25,637: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-27 23:21:25,640: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-27 23:21:25,641: INFO: common: created directory at: artifacts]
[2025-04-27 23:21:25,642: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-27 23:21:26,126: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-27 23:22:21,550: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-27 23:22:21,557: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-27 23:22:21,560: INFO: common: created directory at: artifacts]
[2025-04-27 23:22:21,563: INFO: common: created directory at: artifacts/training]
[2025-04-28 00:34:28,737: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-28 00:34:28,748: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-28 00:34:28,752: INFO: common: created directory at: artifacts]
[2025-04-28 00:34:52,074: INFO: common: json file saved at: scores.json]
[2025-04-28 00:34:54,721: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-04-28 00:34:55,356: INFO: builder_impl: Assets written to: /tmp/tmpo8poaijn/model/data/model/assets]
[2025-04-28 00:58:05,928: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-28 00:58:05,932: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-28 00:58:05,936: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-28 00:58:05,936: INFO: common: created directory at: artifacts]
[2025-04-28 00:58:05,937: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-28 00:58:05,937: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-28 00:58:58,402: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-28 00:58:59,240: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-28 00:58:59,240: INFO: main: *******************]
[2025-04-28 00:58:59,241: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-28 00:58:59,242: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-28 00:58:59,243: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-28 00:58:59,244: INFO: common: created directory at: artifacts]
[2025-04-28 00:58:59,244: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-28 00:59:00,639: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-28 00:59:00,955: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-28 00:59:00,955: INFO: main: *******************]
[2025-04-28 00:59:00,955: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-28 00:59:00,958: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-28 00:59:00,960: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-28 00:59:00,960: INFO: common: created directory at: artifacts]
[2025-04-28 00:59:00,960: INFO: common: created directory at: artifacts/training]
[2025-04-28 01:00:15,161: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-28 01:00:15,165: INFO: main: *******************]
[2025-04-28 01:00:15,165: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-04-28 01:00:15,173: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-28 01:00:15,180: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-28 01:00:15,182: INFO: common: created directory at: artifacts]
[2025-04-28 01:00:42,110: INFO: common: json file saved at: scores.json]
[2025-04-28 01:00:42,113: INFO: common: json file saved at: scores.json]
[2025-04-28 01:00:42,114: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-04-28 01:05:58,853: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8089
 * Running on http://192.168.1.15:8089]
[2025-04-28 01:05:58,853: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-04-28 01:06:20,794: INFO: _internal: 127.0.0.1 - - [28/Apr/2025 01:06:20] "POST /predict HTTP/1.1" 200 -]
[2025-04-28 01:23:58,845: INFO: _internal: 127.0.0.1 - - [28/Apr/2025 01:23:58] "POST /predict HTTP/1.1" 200 -]
[2025-04-28 06:44:19,580: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-28 06:44:19,581: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-28 06:44:19,583: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-28 06:44:19,583: INFO: common: created directory at: artifacts]
[2025-04-28 06:44:19,583: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-28 06:44:19,583: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-28 06:45:17,909: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-28 06:45:18,450: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-28 06:45:18,450: INFO: main: *******************]
[2025-04-28 06:45:18,450: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-28 06:45:18,453: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-28 06:45:18,457: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-28 06:45:18,459: INFO: common: created directory at: artifacts]
[2025-04-28 06:45:18,459: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-28 06:45:19,196: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-28 06:45:19,769: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-28 06:45:19,773: INFO: main: *******************]
[2025-04-28 06:45:19,774: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-28 06:45:19,782: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-28 06:45:19,788: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-28 06:45:19,790: INFO: common: created directory at: artifacts]
[2025-04-28 06:45:19,791: INFO: common: created directory at: artifacts/training]
[2025-04-28 06:46:45,821: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-28 06:46:45,821: INFO: main: *******************]
[2025-04-28 06:46:45,821: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-04-28 06:46:45,825: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-28 06:46:45,830: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-28 06:46:45,831: INFO: common: created directory at: artifacts]
[2025-04-28 06:47:00,995: INFO: common: json file saved at: scores.json]
[2025-04-28 06:47:00,997: INFO: common: json file saved at: scores.json]
[2025-04-28 06:47:00,997: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-04-28 06:56:48,678: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-28 06:56:48,679: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-28 06:56:48,680: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-28 06:56:48,680: INFO: common: created directory at: artifacts]
[2025-04-28 06:56:48,681: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-28 06:56:48,681: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-28 06:57:51,553: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-28 06:57:52,263: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-28 06:57:52,263: INFO: main: *******************]
[2025-04-28 06:57:52,263: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-28 06:57:52,265: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-28 06:57:52,267: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-28 06:57:52,267: INFO: common: created directory at: artifacts]
[2025-04-28 06:57:52,267: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-28 06:57:52,892: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-28 06:57:53,195: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-28 06:57:53,195: INFO: main: *******************]
[2025-04-28 06:57:53,195: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-28 06:57:53,200: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-28 06:57:53,202: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-28 06:57:53,202: INFO: common: created directory at: artifacts]
[2025-04-28 06:57:53,202: INFO: common: created directory at: artifacts/training]
[2025-04-28 06:59:05,794: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-28 06:59:05,795: INFO: main: *******************]
[2025-04-28 06:59:05,795: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-04-28 06:59:05,800: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-28 06:59:05,806: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-28 06:59:05,808: INFO: common: created directory at: artifacts]
[2025-04-28 06:59:24,888: INFO: common: json file saved at: scores.json]
[2025-04-28 06:59:24,889: INFO: common: json file saved at: scores.json]
[2025-04-28 06:59:24,889: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-04-28 07:06:53,591: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-04-28 07:06:53,595: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-28 07:06:53,597: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-28 07:06:53,598: INFO: common: created directory at: artifacts]
[2025-04-28 07:06:53,598: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-28 07:06:53,599: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-28 07:07:55,356: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-04-28 07:07:55,805: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-04-28 07:07:55,805: INFO: main: *******************]
[2025-04-28 07:07:55,805: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-04-28 07:07:55,806: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-28 07:07:55,807: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-28 07:07:55,808: INFO: common: created directory at: artifacts]
[2025-04-28 07:07:55,808: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-04-28 07:07:56,240: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-04-28 07:07:56,433: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-04-28 07:07:56,433: INFO: main: *******************]
[2025-04-28 07:07:56,433: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-04-28 07:07:56,434: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-28 07:07:56,435: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-28 07:07:56,435: INFO: common: created directory at: artifacts]
[2025-04-28 07:07:56,435: INFO: common: created directory at: artifacts/training]
[2025-04-28 07:08:45,052: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-04-28 07:08:45,052: INFO: main: *******************]
[2025-04-28 07:08:45,052: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-04-28 07:08:45,055: INFO: common: yaml file: config/config.yaml loaded successfully]
[2025-04-28 07:08:45,058: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-28 07:08:45,058: INFO: common: created directory at: artifacts]
[2025-04-28 07:09:00,291: INFO: common: json file saved at: scores.json]
[2025-04-28 07:09:00,291: INFO: common: json file saved at: scores.json]
[2025-04-28 07:09:00,291: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
